---
title: "TidyTuesday 2022 Week 38"
output: html_document
---

```{r}
library(tidyverse)
library(ggthemes)
library(showtext)
library(ggtext)
library(cowplot)
```
```{r}
### Load data ###

HydroWASTE_v10 <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-09-20/HydroWASTE_v10.csv')

head(HydroWASTE_v10)
```
```{r}
HydroWASTE_v10 |>
  group_by(STATUS) |>
  count()
```
```{r}
df_plot <- HydroWASTE_v10 |>
  filter(! STATUS %in% c("Closed", "Decommissioned", "Non-Operational")) |>
  filter(!is.na(DF)) |>
  select(WASTE_ID, COUNTRY, CNTRY_ISO, WWTP_NAME, LAT_WWTP, LON_WWTP, WASTE_DIS, DF) |>
  mutate(region = COUNTRY)
df_plot |>
  group_by(COUNTRY) |>
  count()
```
```{r}
### Setup ###
fontfamily = "Roboto Condensed"
font_add_google(fontfamily, fontfamily)
fa_brands_path <- systemfonts::font_info(family = "Font Awesome 6 Brands")[["path"]]
font_add(family = "fa-brands", fa_brands_path)

showtext_auto()

europe_countries <- c("Albania", "Latvia", "Andorra", "Liechtenstein", "Lithuania", "Austria", "Luxembourg", "Malta", "Belarus", "Moldova", "Belgium", "Monaco", "Bosnia and Herzegovina", "Montenegro", "Bulgaria", "Netherlands", "Croatia", "Norway", "Cyprus", "Poland", "Czech Republic", "Czech Rep.", "Czechia","Portugal", "Denmark", "Romania", "Estonia", "Finland", "San Marino", "Macedonia", "North Macedonia", "Serbia", "France","Slovakia", "Slovenia", "Germany", "Spain", "Greece", "Hungary", "Sweden", "Switzerland", "Ireland", "Italy", "Ukraine", "Kosovo", "United Kingdom", "UK")

bg_color <- "#52486B"
fg_color <- "#281C44"
```
```{r}
### Load map data ###

europe_map <- map_data("world") |>
  filter(! long > 180,
         region %in% europe_countries,
         ! subregion %in% c("Svalbard"))


europe_data <- df_plot |>
  filter(COUNTRY %in% europe_countries) |>
  filter(DF < 10)

total_n <- nrow(europe_data)
```
```{r}
ggplot(europe_data, aes(x = DF)) +
  geom_histogram()
```
```{r}
europe_data |>
  group_by(COUNTRY) |>
  count()
```

```{r}
### Text plot ###

text_df <- tibble(
  x = 0, y = 0,
  label = str_glue("<span style = 'color:#ffffff;'>**Incomplete removal in wastewater treatment leads to discharge of diluted chemical waste into rivers and seas**</span><br><br><span style = 'color:#ff8000;'>**",toString(total_n),"**</span><span style = 'color:#ffffff;'> **wastewater plants in Europe show a dilution factor less than 10, posing** </span><span style = 'color:#ff8000;'>**high contamination risk**</span>")
)

text_plot <- ggplot(text_df) +
  geom_textbox(
    aes(x = x, y = y, label = label),
    box.color = bg_color,
    fill = bg_color,
    width = unit(8, "lines"),
    family = fontfamily,
    size = 2.5,
    lineheight = 1) +
  coord_cartesian(expand = FALSE, clip = "on") +
  theme_void() +
  theme(plot.background = element_rect(fill = bg_color),
        panel.border = element_blank())
```
```{r}
### Plot ###

europe_plot <-
  europe_map |>
  ggplot(aes(x = long, y = lat, map_id = region))+
  geom_map(map = europe_map,
           fill = fg_color,
           color = bg_color,
           size = 0.05) +
  coord_map("mollweide") +
  theme_map() +
  scale_fill_continuous(guide="none") +
  geom_point(
    data = europe_data,
    aes(x = LON_WWTP, y = LAT_WWTP, color = DF),
    size = 0.65,
    alpha = 0.7) +
  scale_color_gradient(low = "#cc0000", high = "#ffff99", breaks=c(0,2,4,6,8,10), limits=c(0,10)) +
  labs(title = "Wastewater treatment plants in Europe",
       caption = "#TidyTuesday <span style='font-family:\"fa-brands\"'>&#xf099; </span> @lucasbattich<br>Data: Macedo et al (2022)",
       color = "dilution factor") +
  theme(plot.title = element_text(hjust = 0.35,
                                  size = 19,
                                  color = "white",
                                  family = fontfamily,
                                  face = "bold",
                                  margin = margin(15,0,15,0)),
        plot.caption = element_markdown(hjust = 0.45,
                                        size = 6,
                                        color = "white",
                                        family = fontfamily,
                                        face = "bold",
                                        margin = margin(-5,0,12,0),
                                        lineheight = 1.2),
        plot.title.position = "panel",
        legend.position = c(0.77,0.76), #c(0.02,0.46)
        legend.title = element_text(color = "white", size = 9, face="bold", family = fontfamily, angle = 90),
        legend.text = element_text(color = "white", size = 6, face="bold", family = fontfamily),
        legend.key.width = unit(6.5, "point"),
        legend.key.size = unit(12, "point"),
        panel.border = element_blank(),
        plot.margin = margin(0,-15,0,0, "pt"),
        plot.background = element_rect(fill = bg_color)) +
  guides(color = guide_colorbar(title.position = "left",
                                title.hjust = 0.75))
europe_plot
```
```{r}
text_plot <- text_plot + theme(plot.background = element_blank())
plot <- ggdraw() +
  draw_plot(europe_plot) +
  draw_plot(text_plot, x = 0.2, y = .63, width = 0.27, height = 0.3)
```
```{r}
### Save plot ###

showtext_opts(dpi = 300)
save_plot(plot = plot,
          "2022_week38.png",
          base_height = 5,
          dpi = 300)
```
